# Generated by Django 6.0.1 on 2026-01-19 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizly_app", "0002_quizattempt_useranswer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttemptAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected_option", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="useranswer",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="useranswer",
            name="quizly_app__attempt_f8da62_idx",
        ),
        migrations.RemoveIndex(
            model_name="quizattempt",
            name="quizly_app__user_id_0a3262_idx",
        ),
        migrations.RenameField(
            model_name="quizattempt",
            old_name="finished_at",
            new_name="completed_at",
        ),
        migrations.RenameField(
            model_name="quizattempt",
            old_name="current_index",
            new_name="correct_count",
        ),
        migrations.RenameField(
            model_name="quizattempt",
            old_name="is_finished",
            new_name="is_completed",
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="current_question_index",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="total_questions",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(
                fields=["user", "quiz", "is_completed"],
                name="quizly_app__user_id_da56f2_idx",
            ),
        ),
        migrations.AddField(
            model_name="attemptanswer",
            name="attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="quizly_app.quizattempt",
            ),
        ),
        migrations.AddField(
            model_name="attemptanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempt_answers",
                to="quizly_app.question",
            ),
        ),
        migrations.RemoveField(
            model_name="useranswer",
            name="attempt",
        ),
        migrations.RemoveField(
            model_name="useranswer",
            name="question",
        ),
        migrations.AddIndex(
            model_name="attemptanswer",
            index=models.Index(
                fields=["attempt", "question"], name="quizly_app__attempt_7039d2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="attemptanswer",
            constraint=models.UniqueConstraint(
                fields=("attempt", "question"), name="uniq_attempt_question"
            ),
        ),
        migrations.DeleteModel(
            name="UserAnswer",
        ),
    ]
